# ---
# - name: reload firewalld
#   ansible.builtin.service:
#     name: firewalld
#     state: reloaded

# using systemd to reload firewalld
---
- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
